### ISSUE TITLE
Reason for having `setHeight` be a callback in `_getRow` callback

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/hyperlist#24]
When using `generate` we now support returning an object with a height value. However, this used to be a callback and the specific use case is when the height is unknown until the element lands in the DOM.

**Comment by soyuka** [comment]
1. get element (height unknown), just append to the DOM (computes positioning based on itemHeight)
2. get height => compute positioning again => redraw the showed element (here there will probably be a screen flick)

Or we need to:

1. append to the DOM with opacity 0
2. get element height from DOM
3. compute positioning again
4. redraw

Though, those are uneeded steps when height is known, and there will be more rendering.

**Comment by tbranyen** [comment]
What about two passes, first one lays everything out second pass sets correct offsets?

**Comment by tbranyen** [comment]
With this second approach I think it'd be doable without any HyperList code changes.

**Comment by soyuka** [comment]
Yes indeed!
