### ISSUE TITLE
Introduce multiple browser testing

### ISSUE THREAD

**Issue by soyuka** [tbranyen/hyperlist#25]
Like https://www.browserling.com/ for example. Not sure how this can be setup though, and we'd need to ask them for a free open source account.

**Comment by tbranyen** [comment]
I don't want to switch to Karma, so please rule that solution out. It has been a nightmare to maintain across projects for years. If we decide to go down this route (it's going to be a pain to support) I'd highly recommend writing the browser tests outside of the unit tests and to use a common interface like https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html

**Comment by soyuka** [comment]
> I don't want to switch to Karma, so please rule that solution out. It has been a nightmare to maintain across projects for years. 

Haha I sure am aware of this...

mocha has been built to run in the browser, I don't think we need karma for this. Anyway this is out of my scope.

**Comment by stevenvachon** [comment]
There's [puppeteer](https://npmjs.com/puppeteer) and [puppeteer-firefox](https://npmjs.com/puppeteer-firefox) (not yet ready).
