### ISSUE TITLE
First "page" not quite right

### ISSUE THREAD

**Issue by alindsay55661** [tbranyen/hyperlist#31]
First off, excellent work on this much needed utility. 

I am experiencing a strange issue where the first set of data has very odd behavior. In my particular case, if I scroll the data stops displaying at row 57. However, as I keep scrolling, once row 57 reaches the top of the grid, suddenly rows 58-xx become visible as expected. All scrolling works perfectly after this first "page" of data. 

This is also true in reverse. If I scroll backwards everything works perfectly until I hit row 57 (now at the top of the grid). Once I hit that row, rows 58-xx immediately disappear. Continued scrolling brings in rows 0-57. 

Not all sure what might be causing this, but thought I would report.

My grid contains 500k rows btw.

**Comment by soyuka** [comment]
May you provide a fiddle/plunkr with a case reproduction? What version are you using?

Thanks!

**Comment by alindsay55661** [comment]
Ok, plunker created. In this plunker the effected row happens to be 36.

https://plnkr.co/edit/4vvh1pzsMPGoP1JMbB5d?p=preview

Let me know your thoughts, thanks!

**Comment by soyuka** [comment]
May you try my patch https://github.com/tbranyen/hyperlist/pull/32?

**Comment by alindsay55661** [comment]
Works perfectly!
