### ISSUE TITLE
Delayed rendering when scrolling upwards

### ISSUE THREAD

**Issue by fabien** [tbranyen/hyperlist#36]
When scrolling back upwards, I was sometimes missing the topmost item, probably due to this:

https://github.com/tbranyen/hyperlist/blob/master/dist/hyperlist.js#L108

I decided to replace this with the following:

```javascript

var difference = lastRepaint ? scrollTop - lastRepaint : 0; // FIX
if (!lastRepaint || difference < 0 || difference > _this._averageHeight) { ... }

```

This seems to behave much better. Does this make any sense? Thanks for HyperList!

**Comment by soyuka** [comment]
Makes sense. Would you mind issuing a pull request with that patch?

**Comment by fabien** [comment]
I currently don't have the project setup on my machine to run tests and so on.

Would you mind handling it instead?
