### ISSUE TITLE
Dynamic list size from variable length collection

### ISSUE THREAD

**Issue by Zazzzles** [tbranyen/hyperlist#42]
Hi tbranyen, love this project!

I would like to implement this with a streamed collection - i.e. a collection who's size will increase over time. At the moment, a fixed collection size is part of the initialization of the hyperlist plugin. Is there any plans to allow for dynamic list sizing or is there a workaround that I could use?

**Comment by soyuka** [comment]
It's already working, just use the `refresh` method and change your `config.total` value :). 

https://github.com/tbranyen/hyperlist/blob/master/examples/horizontal.html#L75

**Comment by Zazzzles** [comment]
Ah of course - totally missed that. Thanks for an awesome plugin!
