### ISSUE TITLE
position: 'relative' on element

### ISSUE THREAD

**Issue by krunal-sheth** [tbranyen/hyperlist#62]
https://github.com/tbranyen/hyperlist/blob/dda9904308f72b3282671d2488bc65cd74729ded/lib/index.js#L196

why is position:'relative' is set on element? I would like the position on the container element passed in is left alone - there is a need to use the list inside a drop down with lots of element and position:absolute is what i would like for those _one not so common_ cases

**Comment by tbranyen** [comment]
Hi @krunal-sheth how would you propose this tool would work without using `position: relative`? The children are positioned absolutely to make it virtual.
