### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by tdhung80** [tbranyen/hyperlist#64]
Hi,

That is rendering too many elements without removing rendered DOM elements in invisible area from memory.

Regards,
Hung Tran

**Comment by tbranyen** [comment]
@tdhung80 there are some problems with the logic that does the rendering. this projects doesn't get much work as you can imagine. Feel free to poke around in the code and see if you can find a way to improve it. I can help review any changes. My guess is something in the `_renderChunk` method.
