### ISSUE TITLE
Overflow below the waterline who could solve my problem

### ISSUE THREAD

**Issue by Madriix** [tbranyen/hyperlist#70]
Hi
Reproduce the bug on Firefox, it comments on a lot of problems :

![problem](https://user-images.githubusercontent.com/9107640/109256380-2fa5fe80-77f6-11eb-8c88-10f7e515ea2c.jpg)

How to solve this so that it is perfect?
The "overflow" could solve my problem so as not to display 50 excess items at startup

Cdt

**Comment by tbranyen** [comment]
This library is designed to overflow to allow for smooth scrolling. Although I think we could do a lot better at determining how much to actually overflow in either direction. Since we have a generate method, I suppose you could return undefined if the item appears after the height of the window.
