### ISSUE TITLE
Unexpected usage via CommonJS 

### ISSUE THREAD

**Issue by timwis** [tbranyen/hyperlist#9]
If you want to use this library via CommonJS, you need to use the `default` property on the object it exports.

Expected functionality:
```javascript
var HyperList = require('hyperlist')
```
At this point, `HyperList` will be an object with a `default` property. The `default` property contains the actual `HyperList` object described in the documentation.

Current work-around:
```javascript
var HyperList = require('hyperlist').default
```

I assume this has to do with however you're translating the ES2015 `export` into CommonJS as [this line](https://github.com/tbranyen/hyperlist/blob/master/dist/hyperlist.js#L279) appears to be the culprit.

**Comment by tbranyen** [comment]
@timwis Thanks for the issue, this was an oversight, https://www.npmjs.com/package/babel-plugin-add-module-exports should be added to produce a more usable CJS

**Comment by timwis** [comment]
Okay, I'll throw together a PR
